export const NOTIFICATION_TYPES = [
  'order_assigned',
  'order_unassigned',
  'order_completed',
  'order_rescheduled',
  'order_leave',
  'order_unstaffed',
  'order_photo',
  'order_rapport_signed',
  'order_rapport_unsigned',
  'order_enroute',
  'order_arrived',
  'feed_post',
  'feed_comment',
  'feed_resolved',
  'feed_pinned',
  'event_created',
  'event_today',
  'event_rsvp',
  'vehicle_taken',
  'vehicle_returned',
  'team_new_member',
  'project_status',
  'timelog_missing',
] as const

export type NotificationType = (typeof NOTIFICATION_TYPES)[number]

export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  order_assigned: 'Auftrag zugewiesen',
  order_unassigned: 'Auftrag entzogen',
  order_completed: 'Auftrag abgeschlossen',
  order_rescheduled: 'Auftrag verschoben',
  order_leave: 'Urlaub/Krank',
  order_unstaffed: 'Auftrag unbesetzt',
  order_photo: 'Foto hochgeladen',
  order_rapport_signed: 'Rapport unterschrieben',
  order_rapport_unsigned: 'Rapport ohne Unterschrift',
  order_enroute: 'Unterwegs',
  order_arrived: 'Angekommen',
  feed_post: 'Pinnwand-Eintrag',
  feed_comment: 'Pinnwand-Kommentar',
  feed_resolved: 'Pinnwand-Beitrag gelöst',
  feed_pinned: 'Pinnwand-Beitrag angepinnt',
  event_created: 'Neues Event',
  event_today: 'Event heute',
  event_rsvp: 'Event-Zusage',
  vehicle_taken: 'Fahrzeug genommen',
  vehicle_returned: 'Fahrzeug zurückgegeben',
  team_new_member: 'Neuer Mitarbeiter',
  project_status: 'Projekt-Status',
  timelog_missing: 'Zeiterfassung fehlt',
}
